version: 2
jobs:
    build:
        docker:
            -image: circleci/python:3.6.1
        
        working_directory: ~/repo
        
        steps:
            - checkout
            
            - restore_cache:
                keys:
                    -v1-dependencies-{{ checksum "requirements.txt" }}
                    -v1-dependencies-1
            
            - run:
                name: install dependencies
                command: |
                    python3 -m venv .dockerproj
                    . .dockerproj/bin/activate
                    make install
                    
            - save_cache:
                paths:
                    - ./.dockerproj
                key: v1-dependencies-{{ checksum "requirements.txt" }}
            
            - run:
                name: run lint
                command: |
                    . .dockerproj/bin/activate
                    make lint
    